export const Informacion=[{
    matricula:"230023er",
    nombre:'Juan',
    apellidos:'Perez',
    curp:"ju56ddrtgy"
},
{
    matricula:"230023JL",
    nombre:'Pedro',
    apellidos:'Paramo',
    curp:"PEDRERD"
},
{
    matricula:"23002OP",
    nombre:'Luis',
    apellidos:'Cambrano',
    curp:"PIYU3455"
}
]